
[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/generate_pdf/template.pdf","netlify/functions/generate_pdf/NotoSansKR.ttf"]
